import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer
} from 'recharts'


function CategoryChart({ data }) {

    return (

        <div className="chart-card">

            <div className="chart-header">

                <h2>
                    Revenue by Category
                </h2>

                <p>
                    Revenue generated by product category
                </p>

            </div>

            <ResponsiveContainer
                width="100%"
                height={350}
            >

                <BarChart
                    data={data}
                    layout="vertical"
                    margin={{
                        left: 30,
                        right: 20
                    }}
                >

                    <CartesianGrid
                        strokeDasharray="3 3"
                    />

                    <XAxis
                        type="number"
                    />

                    <YAxis
                        type="category"
                        dataKey="category_name"
                        width={100}
                    />

                    <Tooltip
                        formatter={(value) =>
                            `$${Number(value).toLocaleString()}`
                        }
                    />

                    <Bar
                        dataKey="revenue"
                        radius={[0, 4, 4, 0]}
                    />

                </BarChart>

            </ResponsiveContainer>

        </div>

    )
}

export default CategoryChart