import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    CartesianGrid,
    Tooltip,
    ResponsiveContainer
} from 'recharts'

function RegionChart({ data }) {
    return (
        <div className="chart-card">
            <div className="chart-header">
                <h2>Revenue by Region</h2>
                <p>Revenue generated by customer region</p>
            </div>

            <ResponsiveContainer width="100%" height={350}>
                <BarChart data={data}>
                    <CartesianGrid strokeDasharray="3 3" />

                    <XAxis dataKey="region" />

                    <YAxis />

                    <Tooltip
                        formatter={(value) =>
                            `$${Number(value).toLocaleString('en-US', {
                                minimumFractionDigits: 2,
                                maximumFractionDigits: 2
                            })}`
                        }
                    />

                    <Bar
                        dataKey="revenue"
                        radius={[4, 4, 0, 0]}
                    />
                </BarChart>
            </ResponsiveContainer>
        </div>
    )
}

export default RegionChart